### ISSUE TITLE
linux下怎样才能不自动添加iptables规则？

### ISSUE THREAD

**Issue by ekenchan** [ccsexyz/kcpraw#1]
因为每次添加都不准，还要删掉自己手工添加

**Comment by ccsexyz** [comment]
如果不想要的话我可以加一个选项屏蔽掉这个行为,不过为什么添加会不准呢，能把自动添加的和你手动添加的发出来看一下吗

**Comment by ccsexyz** [comment]
@ekenchan 我刚刚改了下添加的 iptables 规则,现在是添加到规则链头部的了,你可以试下,至少我的路由器上现在可以用了

**Comment by ekenchan** [comment]
@ccsexyz 不是，在我的openvz上总是获取到source=localhost

**Comment by ccsexyz** [comment]
你把自动加的规则打印出来看下吧

**Comment by ccsexyz** [comment]
source=localhost说明你参数没填服务器IP,localaddr要ip:port一起填才行

**Comment by ekenchan** [comment]
我明白了，是跟server端 -l 后面的网址有关，现在正确了，谢谢
