### ISSUE TITLE
Host字段配置是已经去除了么？

### ISSUE THREAD

**Issue by diigu** [ccsexyz/kcpraw#14]
kcpraw# ./kcpraw_server_linux_amd64 -t "127.0.0.1:443" -l "0.0.0.0:8000" --key "xxxx" --crypt xor --mode fast2 --host www.qq.com
Incorrect Usage. flag provided but not defined: -host

Host字段配置是已经去除了么？

**Comment by ccsexyz** [comment]
服务端不需要填 Host 字段

**Comment by diigu** [comment]
get。。我个zz。。。
