### ISSUE TITLE
请提供 windows 预编译版

### ISSUE THREAD

**Issue by soloradish** [ccsexyz/kcpraw#16]
在 release 里面没有提供 windows 的版本， 非 golang 开发者进行编译时会各种撞到墙上。
希望提供一个 windows 的发行版。
感谢。

**Comment by ccsexyz** [comment]
已更新

**Comment by mixool** [comment]
win7 64 闪退了， 太快了，捕捉不到错误 ，怎么办

**Comment by ccsexyz** [comment]
用 cmd 运行

**Comment by ccsexyz** [comment]
![image](https://user-images.githubusercontent.com/13003124/31315567-d2a63fe6-ac4d-11e7-9f28-f311b07dc22d.png)

![image](https://user-images.githubusercontent.com/13003124/31315591-1a9e38b2-ac4e-11e7-9f41-60410f2eef18.png)

**Comment by mixool** [comment]
debian 8 64 server:
root@ppub:~# /root/kcpraw_server_linux_amd64 -l 173.254.232.52:81 -t :10086 --key secret --mtu 1200 --mode fast2 --ds 0 --ps 0 --nocomp
2017/10/08 05:46:49 version: 20170930
2017/10/08 05:46:49 listening on: 173.254.232.52:81
2017/10/08 05:46:49 target: :10086
2017/10/08 05:46:49 encryption: aes
2017/10/08 05:46:49 nodelay parameters: 1 20 2 1
2017/10/08 05:46:49 sndwnd: 1024 rcvwnd: 1024
2017/10/08 05:46:49 compression: false
2017/10/08 05:46:49 mtu: 1200
2017/10/08 05:46:49 datashard: 0 parityshard: 0
2017/10/08 05:46:49 acknodelay: false
2017/10/08 05:46:49 dscp: 0
2017/10/08 05:46:49 sockbuf: 4194304
2017/10/08 05:46:49 keepalive: 10
2017/10/08 05:46:49 snmplog: 
2017/10/08 05:46:49 snmpperiod: 60
2017/10/08 05:46:49 pprof: false

win7 64 client:
[![client.PNG](https://ooo.0o0.ooo/2017/10/08/59d9f6928a1c3.png)](https://ooo.0o0.ooo/2017/10/08/59d9f6928a1c3.png)

**Comment by ccsexyz** [comment]
确定服务端运行起来了 & 防火墙开放了对应的端口？
我扫了下这个 IP 的 TCP 端口只有 22 是开放的。

**Comment by mixool** [comment]
默认开启了所有端口的，我设置SS或者原版kcptun什么的都不需要去管防火墙。
刚才我结束了那个进程。
现在我
`nohup /root/kcpraw_server_linux_amd64 -l 173.254.232.52:8088 -t :10086 --key secret --mtu 1200 --mode fast2 --ds 0 --ps 0 --nocomp >log.txt &`
你看看能不能连接

**Comment by ccsexyz** [comment]
额，很奇怪啊，看起来这个可执行文件是上游 kcptun 的可执行文件，但是为什么文件名是 kcpraw***
kcpraw 的日志输出长这样，明显很多输出字段不一样
<img width="715" alt="2017-10-08 7 06 27" src="https://user-images.githubusercontent.com/13003124/31316218-f48db496-ac5b-11e7-9c46-dda4e7f12307.png">

**Comment by mixool** [comment]
泪奔。。搞了2个小时，我的锅！感谢！我自己用脚本， 把2个文件搞混了，逃...

**Comment by soloradish** [comment]
感谢啦, 我先把这个 close 了.
