### ISSUE TITLE
请问如何在debian上编译windows的执行文件ORZ

### ISSUE THREAD

**Issue by staalu** [ccsexyz/kcpraw#17]
直接执行build-release.sh只能编译出linux版本

报错
gcc: error: unrecognized command line option ‘-mthreads’
尝试google这个错误
然后去安装了
apt-get install gcc-multilib
apt-get install gcc-mingw-w64

但是还是不行 仍然是一样的报错

**Comment by staalu** [comment]
不会写个go >_<

**Comment by ccsexyz** [comment]
我也不会

**Comment by staalu** [comment]
什么鬼!???

**Comment by ccsexyz** [comment]
我都是在 windows 机器上编译 win 版本，Mac 机器上编译 darwin 版本的。

**Comment by staalu** [comment]
...这个  是不能交叉编译的吗 ... 明明build-release.sh里面有去尝试编译windows版本的二进制文件啊

**Comment by staalu** [comment]
TAT 我再研究下

**Comment by ccsexyz** [comment]
非 Linux 下依赖了一个 C 库，没办法

**Comment by ccsexyz** [comment]
为啥会需要在 Linux 环境下编译 winodws 可执行程序

**Comment by staalu** [comment]
>_< 因为我win10没有装go
linux上之前编译kcptun的时候装了个

**Comment by ccsexyz** [comment]
直接用我编译好的吧，windows 上搭编译 gopacket/pcap 的环境也挺麻烦的。

**Comment by staalu** [comment]
咦 我昨天都没看到windows版啊

**Comment by staalu** [comment]
刚刚放上去的样子XD 谢谢
