### ISSUE TITLE
可否增加一个端口转发功能，以便更好的伪装HOST

### ISSUE THREAD

**Issue by mixool** [ccsexyz/kcpraw#18]
使用KCPRAW一天多，很稳定，感谢！
有个问题：客户端使用`--host www.zhihu.com`选项，GFW可以看到我的服务器IP，然后检测发现并不是www.zhihu.com,然后就可以把我们来伤害 --!
魔法师搞个端口转发功能，这样在服务端其它端口搞个网站，kcpraw把不正确的请求转发到那个端口，是不是欺骗性更好。
ssr|ss obfs|goproxy 好像都有这个功能，但是没有KCPRAW的加速效果。
魔法师有计划实现吗？

**Comment by ccsexyz** [comment]
如果你有这方面的担心我觉得直接在客户端使用 nohttp 选项禁用掉 http 伪装就行了。
其实程序里实现的 http 伪装并不是很完善，是当初春节的时候我为了欺骗运营商的计费系统搞出来的，并不适合用来欺骗防火墙。
