### ISSUE TITLE
服务端的proxy参数的作用是什么

### ISSUE THREAD

**Issue by mixool** [ccsexyz/kcpraw#19]
--pprof   --proxy    --ssproxy那几个参数不知道怎么用。
是可以把kcpraw作为ss的服务端还是转发到ss还是前置代理?
如果是转发到ss，-t 参数就不需要了?

**Comment by ccsexyz** [comment]
--proxy 和 --ssproxy 在服务端集成了默认的 socks/http 代理 和 shadowsocks 代理

是的开启之后 -t 参数就没用了

**Comment by mixool** [comment]
服务端参数
`./kcpraw_server_linux_amd64 -l vps:3399 --ssproxy 0.0.0.0:9443 --ssmethod chacha20-ietf-ploy1305 --sskey passwd`
运行显示：
```
pprof listen at: 
default proxy: false
shadowsocks proxy: false
shadowsocks method: chacha20-ietf-ploy1305
shadowsocks key: passwd
```
不成功

**Comment by ccsexyz** [comment]
额, ssproxy 这个参数不需要跟地址,是个布尔值,我代码里命令行参数那里写的时候写错了,刚在这个commit里https://github.com/ccsexyz/kcpraw/commit/2eaa086e920eb23a15f700c5669c7706edf058a6修复了,因为我一直是用配置文件运行的所以没发现

**Comment by ccsexyz** [comment]
另外,ssmethod 支持的加密方式为"aes-128/192/256-ctr aes-128/192/256-cfb chacha20 chacha20-ietf rc4-md5 salsa20 "
这个参数推荐不填,不填的话你用"aes-128/192/256-cfb chacha20 chacha20-ietf rc4-md5 salsa20"这些加密方式里面任意一种去连接都是ok的.

**Comment by mixool** [comment]
这样SS服务只服务器开放的吧？
成功食用，可以不安装SS服务端了，挺方便。

**Comment by ccsexyz** [comment]
是的
不过为啥不直接暴露 socks/http 代理的端口呢,我觉得 shadowsocks 一层加密再套一层 kcptun 的加密好蛋疼啊.

**Comment by mixool** [comment]
因为不是很懂加密啊安全那些问题，心理面觉得多个套安全点吧，我多试试，看看怎么好使怎么使。感谢解答～

**Comment by mixool** [comment]
服务端：
`/kcpraw_server_linux_amd64 -l "VPS_IP:PORT" --proxy socks5`
客户端
`kcpraw_client_windows_amd64 -l 127.0.0.1:1080 -r VPS_IP:PORT`
才发现都不用装其它什么就可以使用了~.~

**Comment by ccsexyz** [comment]
--proxy 后面不需要跟 socks5

**Comment by eromoe** [comment]
pprof  看了下说是go 的性能监控包， 具体怎么使用啊？是不是可以起一个性能监控服务，然后可视化观察效果？

**Comment by ccsexyz** [comment]
http://www.cnblogs.com/yjf512/archive/2012/12/27/2835331.html

**Comment by eromoe** [comment]
居然是嵌个包，直接就提供一个web界面。。。go真是方便啊
