### ISSUE TITLE
能否支持监听 0.0.0.0

### ISSUE THREAD

**Issue by zhu327** [ccsexyz/kcpraw#20]
能否支持 -l 0.0.0.0:29000 , 在docker容器里运行不能指定ip地址

另外导出的端口29000应该还是udp吧?

**Comment by ccsexyz** [comment]
不建议在容器里使用，能问下为什么需要在容器里运行吗？

**Comment by ccsexyz** [comment]
我看了下是想一个容器同时起 ss 和 kcptun 对吧，其实我的 fork 自带这个功能，参见 https://github.com/ccsexyz/kcpraw/issues/19

**Comment by zhu327** [comment]
因为只有容器环境orz...

**Comment by ccsexyz** [comment]
orz... 我当初为了在樱花 docker 中使用开发过一个能够在容器环境中运行的版本，事实证明我太年轻了，樱花 docker 前面有一层 haproxy 之类的代理，基本无法使用，所以后来我把代码删掉了。

**Comment by ccsexyz** [comment]
买个 VPS 吧

**Comment by zhu327** [comment]
我是在bluemix的kubernetes里跑, 用的是一个老版本的kcptun, 一直很稳定, 最近不是墙升级了嘛, 就悲剧了, 所以想试试你这个

**Comment by ccsexyz** [comment]
实现起来倒是很简单，等我重构 rawcon 的时候顺手把这个功能做了吧

**Comment by zhu327** [comment]
我可以通过先获取到容器的ip然后再启动kcpraw了, 但是疑问的是, 我在docker中EXPOSE的port 29000 应该是tcp还是udp呢

**Comment by ccsexyz** [comment]
tcp

**Comment by zhu327** [comment]
请问启动exit status 3 是由于什么原因导致的呢?

./kcpraw_server_linux_amd64 -l 172.17.0.2:3306 -t 127.0.0.1:443 --crypt none --mtu 1200 --mode fast2 --ds 0 --ps 0 --nocomp

2017/10/11 02:45:51.755745 main.go:357: version: 20170930
2017/10/11 02:45:51.762965 main.go:137: exit status 3
net.ListenRAW
github.com/ccsexyz/kcp-go-raw.ListenRAW
	/Users/mofashi/go/src/github.com/ccsexyz/kcp-go-raw/sess.go:143
github.com/ccsexyz/kcp-go-raw.ListenWithOptions
	/Users/mofashi/go/src/github.com/ccsexyz/kcp-go-raw/sess.go:159
main.main.func1
	/Users/mofashi/go/src/github.com/ccsexyz/kcpraw/server/main.go:388
github.com/urfave/cli.HandleAction
	/Users/mofashi/go/src/github.com/urfave/cli/app.go:490
github.com/urfave/cli.(*App).Run
	/Users/mofashi/go/src/github.com/urfave/cli/app.go:264
main.main
	/Users/mofashi/go/src/github.com/ccsexyz/kcpraw/server/main.go:461
runtime.main
	/usr/local/Cellar/go/1.9/libexec/src/runtime/proc.go:185
runtime.goexit
	/usr/local/Cellar/go/1.9/libexec/src/runtime/asm_amd64.s:2337

**Comment by ccsexyz** [comment]
无法操作 iptables 导致的启动失败
现有的程序不改是无法在 docker 里直接运行的，需要在ListenRAW函数里监听一个对应端口的TCP套接字，由内核去做三次握手。
欢迎 fork (& pr)

**Comment by zhu327** [comment]
好吧, 不折腾了... 还不会写go

**Comment by mukaiu** [comment]
感觉还挺需要的，docker方便，尝试pr下
