### ISSUE TITLE
compatibility with  kcptun 

### ISSUE THREAD

**Issue by eromoe** [ccsexyz/kcpraw#21]
`./kcpraw_server_linux_386 -l :2000`

got error:

```

2017/10/11 13:18:10.850982 main.go:357: version: 20171010
2017/10/11 13:18:10.875506 main.go:137: You must set the addr to ip:port
checkAddr
github.com/ccsexyz/kcp-go-raw.ListenRAW
        /Users/mofashi/go/src/github.com/ccsexyz/kcp-go-raw/sess.go:149
github.com/ccsexyz/kcp-go-raw.ListenWithOptions
        /Users/mofashi/go/src/github.com/ccsexyz/kcp-go-raw/sess.go:170
main.main.func1
        /Users/mofashi/go/src/github.com/ccsexyz/kcpraw/server/main.go:390
github.com/urfave/cli.HandleAction
        /Users/mofashi/go/src/github.com/urfave/cli/app.go:490
github.com/urfave/cli.(*App).Run
        /Users/mofashi/go/src/github.com/urfave/cli/app.go:264
main.main
        /Users/mofashi/go/src/github.com/ccsexyz/kcpraw/server/main.go:463
runtime.main
        /usr/local/Cellar/go/1.9/libexec/src/runtime/proc.go:185
runtime.goexit
        /usr/local/Cellar/go/1.9/libexec/src/runtime/asm_386.s:1635
```

`./kcpraw_server_linux_386 -l 0.0.0.0:2000`  error too, must use  external ip.

Hope can keep compatibility with  kcptun .

**Comment by ccsexyz** [comment]
This will be fixed soon.
By the way, I don't think it's necessary to keep compatible.

**Comment by eromoe** [comment]
Compatibility means you can share the config.json , it is kind to ones who come from kcptun.  Like ssr to ss.

**Comment by ccsexyz** [comment]
Maybe I should fix my words. I it's not necessary to keep 100% compatible. Because I choose a different implementation approach,  which means that there are different restrictions.

**Comment by ccsexyz** [comment]
fixed. https://github.com/ccsexyz/rawcon/commit/4572fce8dec0a472c6d247317cabc46da26a6a48  
try the newest releases for linux amd64 and 386:
https://github.com/ccsexyz/kcpraw/releases/download/v20170930/kcpraw-linux-amd64-20171011.tar.gz
https://github.com/ccsexyz/kcpraw/releases/download/v20170930/kcpraw-linux-386-20171011.tar.gz
