### ISSUE TITLE
请帮忙看看是什么原因造成的，不能连接，谢谢

### ISSUE THREAD

**Issue by wansen** [ccsexyz/kcpraw#22]
VPS:centos7 客户端：win10X64
vps配置：
{
    "listen": "VPS:8000",
    "target": ":23456",
    "key": "passward",
    "crypt": "salsa20",
    "mode": "fast3",
    "mtu": 1350,
    "nocomp": true,
    "ssproxy": true,
    "ssmethod":"chacha20-ietf-poly1305",
    "sskey": "passward---"
}

vps日志：
2017/10/11 05:35:15.091239 main.go:357: version: 20171010
2017/10/11 05:35:15.104293 main.go:392: listening on: VPS:8000
2017/10/11 05:35:15.104340 main.go:393: target: :23456
2017/10/11 05:35:15.104357 main.go:394: encryption: salsa20
2017/10/11 05:35:15.104374 main.go:395: nodelay parameters: 1 10 2 1
2017/10/11 05:35:15.104383 main.go:396: sndwnd: 1024 rcvwnd: 1024
2017/10/11 05:35:15.104391 main.go:397: compression: false
2017/10/11 05:35:15.104398 main.go:398: mtu: 1350
2017/10/11 05:35:15.104406 main.go:399: datashard: 10 parityshard: 3
2017/10/11 05:35:15.104414 main.go:400: acknodelay: false
2017/10/11 05:35:15.104421 main.go:401: dscp: 0
2017/10/11 05:35:15.104429 main.go:402: sockbuf: 4194304
2017/10/11 05:35:15.104436 main.go:403: keepalive: 10
2017/10/11 05:35:15.104443 main.go:404: snmplog: 
2017/10/11 05:35:15.104451 main.go:405: snmpperiod: 60
2017/10/11 05:35:15.104458 main.go:406: usemul: false
2017/10/11 05:35:15.104465 main.go:407: udp mode: false
2017/10/11 05:35:15.104473 main.go:408: pprof listen at: 
2017/10/11 05:35:15.104480 main.go:409: default proxy: false
2017/10/11 05:35:15.104488 main.go:410: shadowsocks proxy: true
2017/10/11 05:35:15.104495 main.go:411: shadowsocks method: chacha20-ietf-poly1305
2017/10/11 05:35:15.104503 main.go:412: shadowsocks key: passward---

client端配置：
{
    "localaddr": "127.0.0.1:12345",
    "remoteaddr": "VPS:8000",
    "key": "passward",
    "crypt": "salsa20",
    "mode": "fast3",
    "mtu": 1350,
    "nocomp": true,
    "host": "www.icloud.com"
}

client日志：
2017/10/11 17:38:23.980310 main.go:318: version: 20171008
2017/10/11 17:38:24.016405 main.go:358: listening on: 127.0.0.1:12345
2017/10/11 17:38:24.016405 main.go:359: encryption: salsa20
2017/10/11 17:38:24.016405 main.go:360: nodelay parameters: 1 10 2 1
2017/10/11 17:38:24.016405 main.go:361: remote address: VPS:8000
2017/10/11 17:38:24.016405 main.go:362: sndwnd: 128 rcvwnd: 512
2017/10/11 17:38:24.016405 main.go:363: compression: false
2017/10/11 17:38:24.016405 main.go:364: mtu: 1350
2017/10/11 17:38:24.016405 main.go:365: datashard: 10 parityshard: 3
2017/10/11 17:38:24.016405 main.go:366: acknodelay: false
2017/10/11 17:38:24.016405 main.go:367: dscp: 0
2017/10/11 17:38:24.016405 main.go:368: sockbuf: 4194304
2017/10/11 17:38:24.016405 main.go:369: keepalive: 10
2017/10/11 17:38:24.016405 main.go:370: conn: 1
2017/10/11 17:38:24.016405 main.go:371: autoexpire: 0
2017/10/11 17:38:24.016405 main.go:372: snmplog: 
2017/10/11 17:38:24.016405 main.go:373: snmpperiod: 60
2017/10/11 17:38:24.016405 main.go:374: scavengettl: 600
2017/10/11 17:38:24.016405 main.go:375: mulconn: 0
2017/10/11 17:38:24.016405 main.go:376: udp mode: false
2017/10/11 17:38:24.016405 main.go:377: pprof listen at: 
2017/10/11 17:38:24.016405 main.go:378: dummpy: true
2017/10/11 17:38:24.016405 main.go:379: nohttp: true
2017/10/11 17:38:24.016405 main.go:380: httphost:  www.icloud.com
2017/10/11 17:38:24.021420 main.go:90: cannot find correct interface
createConn()
main.main.func1.2
	C:/WhyGo/src/github.com/ccsexyz/kcpraw/client/main.go:406
main.main.func1
	C:/WhyGo/src/github.com/ccsexyz/kcpraw/client/main.go:453
github.com/urfave/cli.HandleAction
	C:/WhyGo/src/github.com/urfave/cli/app.go:490
github.com/urfave/cli.(*App).Run
	C:/WhyGo/src/github.com/urfave/cli/app.go:264
main.main
	C:/WhyGo/src/github.com/ccsexyz/kcpraw/client/main.go:492
runtime.main
	C:/Go/src/runtime/proc.go:185
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:2337

在vps上通过netstat -antp命令查看，没有看到端口开启。

**Comment by ccsexyz** [comment]
安装 winpcap 了没有？

**Comment by wansen** [comment]
电脑没有安装 winpcap ，不过从安装包内提取了Packet.dll，wpcap.dll
是否是一定要安装？VPS是不是一定要安装Go？
谢谢

**Comment by ccsexyz** [comment]
安装包？哪里的安装包？我的 release 里没有这两个 dll 啊。
是的，是必须装 winpcap 的。Go 不是必须的。

**Comment by wansen** [comment]
winpcap从官网下载后，用7Z打开就可以提取这两个文件。
在VPS端，通过netstat -antp命令看不到kcpraw打开的端口，通过ps -e查看，程序是在运行中，怪得很

**Comment by wansen** [comment]
我在VPS上安装的kcptun，shodowsocks等都能看到打开的端口

**Comment by ccsexyz** [comment]
需要直接运行 winpcap 的可执行文件

**Comment by wansen** [comment]
从这两天开始，我所在的地区udp就受到干扰，面obfs在windows端怎么配置都不成，也查了不少网站，同样配置，手机上正常，windows不正常，我也是无奈啊

**Comment by wansen** [comment]
好的

**Comment by wansen** [comment]
电脑端安装完成winpcap后，还是显示如下 log
2017/10/11 20:18:32.461257 main.go:90: retry too many times and con't capture anything
createConn()
main.main.func1.2
	C:/WhyGo/src/github.com/ccsexyz/kcpraw/client/main.go:406
main.main.func1
	C:/WhyGo/src/github.com/ccsexyz/kcpraw/client/main.go:453
github.com/urfave/cli.HandleAction
	C:/WhyGo/src/github.com/urfave/cli/app.go:490
github.com/urfave/cli.(*App).Run
	C:/WhyGo/src/github.com/urfave/cli/app.go:264
main.main
	C:/WhyGo/src/github.com/ccsexyz/kcpraw/client/main.go:492
runtime.main
	C:/Go/src/runtime/proc.go:185
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:2337

**Comment by wansen** [comment]
看到了，还少一步，compile gopacket on windows

**Comment by ccsexyz** [comment]
额，后面是讲从源码编译的，不需要管

**Comment by wansen** [comment]
那问题是电脑上日志显示如下：
2017/10/11 20:18:29.337712 main.go:318: version: 20171008
2017/10/11 20:18:29.362778 main.go:358: listening on: 127.0.0.1:12345
2017/10/11 20:18:29.362778 main.go:359: encryption: salsa20
2017/10/11 20:18:29.362778 main.go:360: nodelay parameters: 1 10 2 1
2017/10/11 20:18:29.362778 main.go:361: remote address: VPS:8080
2017/10/11 20:18:29.362778 main.go:362: sndwnd: 128 rcvwnd: 512
2017/10/11 20:18:29.362778 main.go:363: compression: false
2017/10/11 20:18:29.362778 main.go:364: mtu: 1350
2017/10/11 20:18:29.362778 main.go:365: datashard: 10 parityshard: 3
2017/10/11 20:18:29.362778 main.go:366: acknodelay: false
2017/10/11 20:18:29.362778 main.go:367: dscp: 0
2017/10/11 20:18:29.362778 main.go:368: sockbuf: 4194304
2017/10/11 20:18:29.362778 main.go:369: keepalive: 10
2017/10/11 20:18:29.362778 main.go:370: conn: 1
2017/10/11 20:18:29.362778 main.go:371: autoexpire: 0
2017/10/11 20:18:29.362778 main.go:372: snmplog: 
2017/10/11 20:18:29.362778 main.go:373: snmpperiod: 60
2017/10/11 20:18:29.362778 main.go:374: scavengettl: 600
2017/10/11 20:18:29.362778 main.go:375: mulconn: 0
2017/10/11 20:18:29.362778 main.go:376: udp mode: false
2017/10/11 20:18:29.362778 main.go:377: pprof listen at: 
2017/10/11 20:18:29.362778 main.go:378: dummpy: true
2017/10/11 20:18:29.362778 main.go:379: nohttp: true
2017/10/11 20:18:29.362778 main.go:380: httphost:  www.icloud.com
2017/10/11 20:18:32.461257 main.go:90: retry too many times and con't capture anything
createConn()
main.main.func1.2
	C:/WhyGo/src/github.com/ccsexyz/kcpraw/client/main.go:406
main.main.func1
	C:/WhyGo/src/github.com/ccsexyz/kcpraw/client/main.go:453
github.com/urfave/cli.HandleAction
	C:/WhyGo/src/github.com/urfave/cli/app.go:490
github.com/urfave/cli.(*App).Run
	C:/WhyGo/src/github.com/urfave/cli/app.go:264
main.main
	C:/WhyGo/src/github.com/ccsexyz/kcpraw/client/main.go:492
runtime.main
	C:/Go/src/runtime/proc.go:185
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:2337

还是要请教你。

**Comment by ccsexyz** [comment]
这个暂时判断不出是哪里的问题，稍后我会加一些日志试试。
抱歉

**Comment by wansen** [comment]
谢谢，麻烦你了

**Comment by ccsexyz** [comment]
试试这个,看下会有啥输出
[kcpraw_client_windows_amd64.zip](https://github.com/ccsexyz/kcpraw/files/1376088/kcpraw_client_windows_amd64.zip)

**Comment by fcying** [comment]
我这边也冒出这个问题了-_-  昨天用的还是好好的, 用管理员启动无效
```
2018/01/15 14:32:42.960298 main.go:649: pprof listen at: 
2018/01/15 14:32:42.960298 main.go:650: dummpy: true
2018/01/15 14:32:42.960298 main.go:651: obfs: 
2018/01/15 14:32:42.960298 main.go:652: httphost: 
2018/01/15 14:32:42.960298 main.go:653: proxy: false
2018/01/15 14:32:42.960298 main.go:654: proxylist: 
2018/01/15 14:32:42.960298 main.go:655: chnroute: 
2018/01/15 14:32:42.960298 main.go:656: udprelay: false
2018/01/15 14:32:43.440771 main.go:315: cannot find correct interface
createConn()
main.main.func1.2
	D:/workspace/go/src/github.com/ccsexyz/kcpraw/client/main.go:715
main.main.func1.5
```

**Comment by fcying** [comment]
貌似是公司网络的问题....家里连接就是正常的....
在公司用原版kcp也能连上(虽然连一会就掉线)
