### ISSUE TITLE
171008 win版本這是有內存漏了?

### ISSUE THREAD

**Issue by staalu** [ccsexyz/kcpraw#23]
運行兩天後內存佔用飆升到接近1G  查了一下好像是go語言的垃圾回收機制的鍋?

聯想到chrome吃內存的毛病了

**Comment by ccsexyz** [comment]
应该是我的问题，等我看眼最近的变更

**Comment by ccsexyz** [comment]
并没有看出什么有问题的变更，这样吧，你用带pprof后缀的程序重新运行，增加一个新的参数 --pprof 127.0.0.1:8000，等到运行一段时间又出现内存泄露后，用浏览器访问http://127.0.0.1:8000/debug/pprof/heap 这个地址，把输出结果发一下

**Comment by staalu** [comment]
等我把這個本子拖完...

**Comment by staalu** [comment]
跑起来了 现在刚启动 占用内存50MB不到 等他涨到200MB+我就发输出给你

**Comment by ccsexyz** [comment]
好的。
按理说不应该呀，非Linux下都是用的同一套代码，mac下我一直在使用，一般使用中的程序内存占用都是稳定在50~60M左右的。

**Comment by ccsexyz** [comment]
4个小时了还没到200MB看来这个问题复现不了了

**Comment by staalu** [comment]
穩定復現的啦  我忘了這事情去做別的了

現在已經增長到400MB了 我看看怎麼發給你

**Comment by ccsexyz** [comment]
可以把网页里的内容保存到文本文件里，然后把文件贴到 issue 里，如果 txt 不行就压缩成 zip

**Comment by staalu** [comment]
暈 你這半夜還在啊

**Comment by ccsexyz** [comment]
你不也在嘛

**Comment by staalu** [comment]
[XX11.txt](https://github.com/ccsexyz/kcpraw/files/1383397/XX11.txt)
[xx12.txt](https://github.com/ccsexyz/kcpraw/files/1383399/xx12.txt)

**Comment by staalu** [comment]
12是我的啟動命令參數

**Comment by staalu** [comment]
我跑了兩個客戶端連不同的出口  都會這樣漏
![x2](https://user-images.githubusercontent.com/5842435/31557847-0c065dec-b07d-11e7-954d-dfddbd2b4645.png)

**Comment by staalu** [comment]
漏多少跟訪問流量多少正相關的樣子

用組策略在win10裡面啟動的時候執行兩個BAT這種方式

**Comment by ccsexyz** [comment]
找到了一些内存分配的比较多的地方，算是一个已知缺陷吧，会在之后重构 rawcon 的时候改掉

**Comment by ccsexyz** [comment]
另外数据流压缩一般建议关掉，因为通过的流量基本上都是已经压缩过的或者是加密过的流量，再压缩一遍也没什么卵用

**Comment by staalu** [comment]
順便求--pid參數XD

**Comment by ccsexyz** [comment]
啊，没有这个参数吧？

**Comment by staalu** [comment]
所以才求加啊  --pid filepath  指定pid文件位置
方便用腳本檢測進程是否在運行 因為之前偶發過 linuxserver端或者client端無故消失掉的狀況
不清楚windows下有沒有類似機制 我好像沒在windows下的軟件上見過

另外 我發現 windows下這內存漏掉後會明顯拖慢運行
具體表現就是
剛剛已經漏到900多MB內存   鼠標的平滑度開始受影響  一卡一卡的 雖然我內存還有10多G空著

**Comment by ccsexyz** [comment]
900MB 的现场还在吗？顺便你 windows 上装了 Go 吗？
我是自己写了个程序，client 挂了就会自动把他拉起来。
我觉得这个意义不是很大其实，所以不打算做。

**Comment by staalu** [comment]
...現場已經沒了... 不過我掛一天到明天起來肯定又是900MB

**Comment by ccsexyz** [comment]
装个 Go 吧，也不是很麻烦，主要是为了用 go tool pprof 命令

**Comment by staalu** [comment]
![default](https://user-images.githubusercontent.com/5842435/31572538-510e8154-b0db-11e7-8ebd-a97a90f54e0f.png)

這個? 1.9.1? go這坑版本號有影響嗎?

**Comment by ccsexyz** [comment]
对的，没有影响，不需要你编译，只需要到时候看下 go tool pprof 的结果就好了

**Comment by staalu** [comment]
![default](https://user-images.githubusercontent.com/5842435/31572613-eb0e5012-b0dc-11e7-84a9-cafa9264000e.png)
然後應該怎樣調試?

**Comment by ccsexyz** [comment]
分别执行这三个命令
```
8231  go tool pprof --alloc_objects http://localhost:7080/debug/pprof/heap
 8232  go tool pprof --inuse_space http://localhost:7080/debug/pprof/heap
 8233  go tool pprof  http://localhost:7080/debug/pprof/heap
```

执行后会进入一个交互式的shell，输入 top20 看看结果

```
(pprof) top20
Showing nodes accounting for 17384.97kB, 100% of 17384.97kB total
      flat  flat%   sum%        cum   cum%
 9728.34kB 55.96% 55.96%  9728.34kB 55.96%  fmt.Sprintf /usr/local/Cellar/go/1.9/libexec/src/fmt/print.go
 4096.12kB 23.56% 79.52%  5632.15kB 32.40%  github.com/google/gopacket/layers.errorFunc /Users/mofashi/go/src/github.com/google/gopacket/layers/enums.go
 1536.02kB  8.84% 88.35%  1536.02kB  8.84%  errors.New /Users/mofashi/go/src/github.com/google/gopacket/layers/arp.go (inline)
 1475.64kB  8.49% 96.84%  1475.64kB  8.49%  bytes.makeSlice /usr/local/Cellar/go/1.9/libexec/src/bytes/buffer.go
  548.84kB  3.16%   100%   548.84kB  3.16%  github.com/ccsexyz/smux.(*Session).sendLoop /Users/mofashi/go/src/github.com/ccsexyz/smux/session.go
         0     0%   100%  1475.64kB  8.49%  bytes.(*Buffer).Write /usr/local/Cellar/go/1.9/libexec/src/bytes/buffer.go
         0     0%   100%  1475.64kB  8.49%  bytes.(*Buffer).grow /usr/local/Cellar/go/1.9/libexec/src/bytes/buffer.go
         0     0%   100% 15360.48kB 88.35%  github.com/ccsexyz/kcp-go-raw.init <autogenerated>
         0     0%   100% 15360.48kB 88.35%  github.com/ccsexyz/rawcon.init <autogenerated>
         0     0%   100%  1475.64kB  8.49%  github.com/ccsexyz/smux.(*Session).recvLoop /Users/mofashi/go/src/github.com/ccsexyz/smux/session.go
         0     0%   100%  1475.64kB  8.49%  github.com/ccsexyz/smux.(*Stream).pushBytes /Users/mofashi/go/src/github.com/ccsexyz/smux/stream.go
         0     0%   100% 15360.48kB 88.35%  github.com/google/gopacket/layers.init <autogenerated>
         0     0%   100% 15360.48kB 88.35%  github.com/google/gopacket/layers.init.0 /Users/mofashi/go/src/github.com/google/gopacket/layers/enums.go
         0     0%   100% 15360.48kB 88.35%  main.init <autogenerated>
         0     0%   100% 15360.48kB 88.35%  runtime.main /usr/local/Cellar/go/1.9/libexec/src/runtime/proc.go
(pprof)
```

看下这三条命令执行 top20 输出是怎样的

**Comment by staalu** [comment]
[v2.txt](https://github.com/ccsexyz/kcpraw/files/1384422/v2.txt)

**Comment by ccsexyz** [comment]
现在看起来占用的内存还不是很多，等一天等内存涨起来了再看吧

**Comment by ccsexyz** [comment]
不科学，我这边看 u2b 4k 也就 60~70 MB，虽然我没开 FEC

**Comment by staalu** [comment]
已經漲到245MB啦 我看看輸出

**Comment by staalu** [comment]
![default](https://user-images.githubusercontent.com/5842435/31573199-68ea9b56-b0e9-11e7-8073-14a760815079.png)
[V3.txt](https://github.com/ccsexyz/kcpraw/files/1384445/V3.txt)

如圖 200MB內存佔用的時候

**Comment by ccsexyz** [comment]
好的，感谢反馈。结果和预想的差不多，应该是没有用零拷贝 api 导致的。还有就是上游 gopacket/pcap 三天前 fix 了一个内存问题，我用最新版本的库编译一下，你看下有没有缓解内存占用的问题。

**Comment by ccsexyz** [comment]
[kcpraw-windows-amd64-20171014.tar.gz.zip](https://github.com/ccsexyz/kcpraw/files/1384449/kcpraw-windows-amd64-20171014.tar.gz.zip)
将后缀 .zip 删掉，其实是 gz 文件
```
sha256
bf493df8b0ff2bd2896b5f809f98b60c2ae00f1e0f48384628b0a802c98e573a *kcpraw-windows-
amd64-20171014.tar.gz
```

**Comment by staalu** [comment]
重开了   

额 我没有重装pcap哦

**Comment by ccsexyz** [comment]
这里指的是 https://github.com/google/gopacket/tree/master/pcap

**Comment by staalu** [comment]
唔 好象还是在漏  开启后几分钟涨到98MB 我再等等看 涨多点了再去抓debug数据

**Comment by staalu** [comment]
你那边无法重现这个BUG吗 用我的启动参数试试看?

**Comment by staalu** [comment]
服务端的参数是
kcpraw_server_linux_amd64 --listen "XXXXXXXX" \
                                                --target "XXXXXXXXXXXXXX" \
                                                --key "XXXXXXXXXXX" \
                                                --crypt "aes-192" \
                                                --mode "fast" \
                                                --datashard 5 \
                                                --parityshard 5 \
                                                --mtu 1317
windows client端的启动参数在上面的xx12.txt里

**Comment by ccsexyz** [comment]
并不能重现，这也很正常，计算机毕竟是玄学

**Comment by staalu** [comment]
你是用的
1.启动命令写进bat文件
2.然后用组策略里面的用户启动时执行这个bat文件
这种方式启动吗?

现在已经涨到183MB了  带pprof这个功能会对此有影响吗?

**Comment by ccsexyz** [comment]
这些都没有影响的，只能等我重构了

**Comment by staalu** [comment]
刚刚涨到200MB 现在减少了!  

我再试一下看看

似乎是因为刚刚我firefox把代理关掉了一会   内存占用降低回了140MB

**Comment by ccsexyz** [comment]
刚发布了一个新的 release,有空的下可以试下,应该内存占用减少不少了,我这边实际使用的话基本稳定在 25M 左右.

**Comment by staalu** [comment]
我試試 prpr

**Comment by staalu** [comment]
应该还是有在漏  不过比之前好了很多 一天才增长到130MB左右 基本不影响使用了 
之前漏多了之后还会导致机器变卡呢 

![xx1122](https://user-images.githubusercontent.com/5842435/31830378-99d4e0a6-b5f2-11e7-86ea-fa58b5981176.png)
[log171020.txt](https://github.com/ccsexyz/kcpraw/files/1402552/log171020.txt)

**Comment by ccsexyz** [comment]
刚发现一个现象,使用了 snappy 数据流压缩的客户端内存确实涨的比较多(但是我忘记使用带 pprof 的程序运行了,所以拿不到具体的数据).
你使用时在两端使用 nocomp 参数关闭这个功能没?如果没有的话我建议关掉数据流压缩

**Comment by staalu** [comment]
prpr 謝謝了
沒有關閉nocomp  就這樣吧  現在這樣已經不影響正常使用了XD
