### ISSUE TITLE
windows 编译配置给一份？

### ISSUE THREAD

**Issue by ohsorry** [ccsexyz/kcpraw#24]

**Comment by ccsexyz** [comment]
去 release 下载

**Comment by ohsorry** [comment]
你没有32位的windows release啊

**Comment by ccsexyz** [comment]
并没有

**Comment by ohsorry** [comment]
那别人32位的windows下你release有啥用

**Comment by ccsexyz** [comment]
那你只能另请高明了

**Comment by ohsorry** [comment]
这种没什么技术含量还挺麻烦的程序必须请你来写啊。

**Comment by ccsexyz** [comment]
![images](https://user-images.githubusercontent.com/13003124/31716470-8950e1bc-b43a-11e7-8e15-58fadcdeed0d.jpeg)
