### ISSUE TITLE
请问是否支持单 server 多客户端？

### ISSUE THREAD

**Issue by kuoruan** [ccsexyz/kcpraw#25]
我准备捋一捋，写个 kcpraw 的安装脚本。
有所有配置选项的文档吗？

**Comment by ccsexyz** [comment]
与 kcptun 用法相同，除了 pprof 参数是个字符串

**Comment by kuoruan** [comment]
也就是不支持单服务端多客户端了？

**Comment by ccsexyz** [comment]
啊？kcptun 不支持吗?还是我们对这个词理解不同

Xingwang Liao <notifications@github.com> 于 2017年10月16日周一 10:20写道：

**Comment by kuoruan** [comment]
1. 我说的单服务端指一个端口，也就是多个客户端连接同一个端口
2. https://github.com/ccsexyz/kcpraw/blob/master/server/main.go#L336 这个 ```multi``` 的意思是只能写 ```multi``` 还是可以写 ss 的所有加密方式？

**Comment by ccsexyz** [comment]
1.这个 kcptun 是支持的，只是多个客户端必须使用相同的加密组合 2.看这个 issue 吧，https://github.com/ccsexyz/kcpraw/issues/19

**Comment by kuoruan** [comment]
难道我的信息过时了？
当初测试的时候，多客户端同时连一个端口是有问题的，莫非现在支持了？

**Comment by ccsexyz** [comment]
具体是什么问题呢

**Comment by kuoruan** [comment]
我又测试了一遍，是我信息过时了，感谢。
