### ISSUE TITLE
windows server 无法启动

### ISSUE THREAD

**Issue by suwubee** [ccsexyz/kcpraw#27]
D:\kcptun\server_windows_amd64.exe -t "127.0.0.1:3389" -l ":3399" -mode fast2
启动正常
D:\kcptun\kcpraw_server_windows_amd64.exe -t "127.0.0.1:3389" -l ":3399" -mode fast
启动报错
`2017/10/19 22:26:41.852336 main.go:412: version: 20171019
2017/10/19 22:26:41.880355 main.go:192: You must set the addr to ip:port
checkAddr
github.com/ccsexyz/kcp-go-raw.ListenRAW
        C:/WhyGo/src/github.com/ccsexyz/kcp-go-raw/sess.go:153
github.com/ccsexyz/kcp-go-raw.ListenWithOptions
        C:/WhyGo/src/github.com/ccsexyz/kcp-go-raw/sess.go:174
main.main.func1
        C:/WhyGo/src/github.com/ccsexyz/kcpraw/server/main.go:445
github.com/urfave/cli.HandleAction
        C:/WhyGo/src/github.com/urfave/cli/app.go:502
github.com/urfave/cli.(*App).Run
        C:/WhyGo/src/github.com/urfave/cli/app.go:268
main.main
        C:/WhyGo/src/github.com/ccsexyz/kcpraw/server/main.go:518
runtime.main
        C:/Go/src/runtime/proc.go:185
runtime.goexit
        C:/Go/src/runtime/asm_amd64.s:2337`
换1008的也是一样

**Comment by suwubee** [comment]
无论如何更改ip:port都没用

**Comment by ccsexyz** [comment]
1.这里检测的是 LocalAddr
2.windows 上 LocalAddr 的 IP 不能设置成 127.0.0.1
3.为啥会想在 windows 上运行服务端程序呢

**Comment by suwubee** [comment]
用3399加速windows的3389端口，因此server在windows上.
我没有运行client，不存在localaddr的检测吧
即 -l ":3399"和-t "127.0.0.1:3389"，应该没有错啊

**Comment by suwubee** [comment]
`D:\kcptun\kcpraw_server_windows_amd64.exe --target 127.0.0.1:3389 --listen :33089 -mode fast2
2017/10/19 23:19:25.405921 main.go:412: version: 20171019
2017/10/19 23:19:25.433940 main.go:192: You must set the addr to ip:port
checkAddr
github.com/ccsexyz/kcp-go-raw.ListenRAW
        C:/WhyGo/src/github.com/ccsexyz/kcp-go-raw/sess.go:153
github.com/ccsexyz/kcp-go-raw.ListenWithOptions
        C:/WhyGo/src/github.com/ccsexyz/kcp-go-raw/sess.go:174
main.main.func1
        C:/WhyGo/src/github.com/ccsexyz/kcpraw/server/main.go:445
github.com/urfave/cli.HandleAction
        C:/WhyGo/src/github.com/urfave/cli/app.go:502
github.com/urfave/cli.(*App).Run
        C:/WhyGo/src/github.com/urfave/cli/app.go:268
main.main
        C:/WhyGo/src/github.com/ccsexyz/kcpraw/server/main.go:518
runtime.main
        C:/Go/src/runtime/proc.go:185
runtime.goexit
        C:/Go/src/runtime/asm_amd64.s:2337`

**Comment by ccsexyz** [comment]
哦，原来 server 端叫 Listen，以前都没注意
