### ISSUE TITLE
FATAL Bad Memory Block.

### ISSUE THREAD

**Issue by kuoruan** [ccsexyz/kcpraw#28]
Win10 客户端疯狂输出 ```FATAL Bad Memory Block.```
但是使用是正常的。

**Comment by ccsexyz** [comment]
搜索了一下似乎是 pcap 这个库的问题，可能没办法在短时间内解决。
疯狂输出的时候程序会崩溃吗？

**Comment by kuoruan** [comment]
换了 npcap，现在看来没问题了，应该就是 Win10Pcap 的问题
