### ISSUE TITLE
能在支持 kcptun 的 Shadowsocks 客户端上使用吗？

### ISSUE THREAD

**Issue by cyio** [ccsexyz/kcpraw#30]
Readme 里没看到相关说明，在电脑或手机上是否能直接使用 SS 客户端，而不是使用命令行？
你们使用 kcpraw 后，手机上用什么？谢谢。

**Comment by ccsexyz** [comment]
现在是无法通过手机上的 shadowsocks 客户端使用的。
在电脑上可以替换 kcptun 的二进制文件，比如 https://github.com/shadowsocks/ShadowsocksX-NG/issues/559

**Comment by cyio** [comment]
![image](https://user-images.githubusercontent.com/3146103/32375820-0472a30c-c071-11e7-97f6-4b57de21aab5.png)

试了下，没成功
1. 替换了二进制文件
2. 服务端命令 `$ ./kcpraw_server_linux_amd64 -l "my-server:80" --proxy`

**Comment by ccsexyz** [comment]
proxy 与 ssproxy 的区别看这个 issue 吧，https://github.com/ccsexyz/kcpraw/issues/19

**Comment by ccsexyz** [comment]
client 加 proxy 的目的是为了消除 socks5 协议的两次握手或者HTTP Connect 的一次握手。与仅仅在 kcpraw-server 端启用 proxy 相比可以降低额外的不必要的延迟。

**Comment by ccsexyz** [comment]
其实我在 root 过的安卓手机上用 termux 跑过，还是可以跑的，不过必须使用分应用代理模式，手动指定需要代理的 app

**Comment by ccsexyz** [comment]
睡眠醒来后等一会才会恢复的问题已经在 https://github.com/ccsexyz/smux/commit/7b7a7a71656c4b39ada516c5918c6a946b48bd06 修复了，你可以编译下最新的代码试下有没有改善
