### ISSUE TITLE
有个参数设置不太明白

### ISSUE THREAD

**Issue by qiuqiuuuu** [ccsexyz/kcpraw#31]
--udp        enable udp mode
这个参数加上是不是ss的udp流量也转为tcp来传送了？不加这个参数速度很慢

还有--mulconn --usemul的使用场景是什么，感觉没什么差别

**Comment by ccsexyz** [comment]
--udp 这个参数的作用是和 kcptun 一样使用 udp 套接字收发数据，不加这个参数会慢这就不太科学了，提供下你的参数我看下
--mulconn、--usemul 主要目的是把一个 kcp 连接的流量分到多个下层的连接上，现在还处在实验阶段，不要用

**Comment by qiuqiuuuu** [comment]
/root/kcpraw_client_linux_amd64 -l 0.0.0.0:12340 -r vpsip:38880 --key secret121 --mode fast3 --host www.icloud.com  

/root/kcpraw_server_linux_amd64 -l vpsip:38880 -t :19999 --key secret121  --mode fast3 

服务器比较渣 ，ping400多，丢10%，kvm的机器没有装锐速bbr之类的加速。kcptun用fast2其他都默认fast.com可以跑到5MB/s ，kcpraw在1MB/s的样子，kcpraw加上-udp --conn 10才能达到kcptun的速度

**Comment by ccsexyz** [comment]
贴下服务端和客户端刚开始运行时候的打印的和参数有关的日志输出吧。不加 --conn 10 也不行吗？
