### ISSUE TITLE
shadowsocks客户端无法连接

### ISSUE THREAD

**Issue by linyuhc001** [ccsexyz/kcpraw#32]
--proxy可以正常使用
如下
./kcpraw_server_linux_amd64 -l 172.30.94.116:8080  --key secret --mtu 1200 --mode fast2 --ds 0 --ps 0 --nocomp --proxy
2017/11/11 21:39:43.724278 main.go:412: version: 20171021
2017/11/11 21:39:43.738584 main.go:449: listening on: 172.30.94.116:8080
2017/11/11 21:39:43.738614 main.go:450: target: 127.0.0.1:12948
2017/11/11 21:39:43.738634 main.go:451: encryption: aes
2017/11/11 21:39:43.738645 main.go:452: nodelay parameters: 1 20 2 1
2017/11/11 21:39:43.738654 main.go:453: sndwnd: 1024 rcvwnd: 1024
2017/11/11 21:39:43.738663 main.go:454: compression: false
2017/11/11 21:39:43.738674 main.go:455: mtu: 1200
2017/11/11 21:39:43.738683 main.go:456: datashard: 0 parityshard: 0
2017/11/11 21:39:43.738692 main.go:457: acknodelay: false
2017/11/11 21:39:43.738700 main.go:458: dscp: 0
2017/11/11 21:39:43.738709 main.go:459: sockbuf: 4194304
2017/11/11 21:39:43.738717 main.go:460: keepalive: 10
2017/11/11 21:39:43.738725 main.go:461: snmplog: 
2017/11/11 21:39:43.738733 main.go:462: snmpperiod: 60
2017/11/11 21:39:43.738740 main.go:463: usemul: false
2017/11/11 21:39:43.738749 main.go:464: udp mode: false
2017/11/11 21:39:43.738757 main.go:465: pprof listen at: 
2017/11/11 21:39:43.738765 main.go:466: default proxy: true
2017/11/11 21:39:43.738773 main.go:467: shadowsocks proxy: false
2017/11/11 21:39:43.738781 main.go:468: shadowsocks method: multi
2017/11/11 21:39:43.738789 main.go:469: shadowsocks key: 
2017/11/11 21:39:57.605208 main.go:493: remote address: 10.126.114.66:14234
2017/11/11 21:40:08.809423 main.go:171: stream opened  (avatars1.githubusercontent.com:443)
2017/11/11 21:40:08.816831 main.go:171: stream opened  (avatars1.githubusercontent.com:443)

同样的端口使用--ssproxy
如下
./kcpraw_server_linux_amd64 -l 172.30.94.116:8080 --ssproxy --sskey passwd
2017/11/11 21:41:41.893273 main.go:412: version: 20171021
2017/11/11 21:41:41.907687 main.go:449: listening on: 172.30.94.116:8080
2017/11/11 21:41:41.907724 main.go:450: target: 127.0.0.1:12948
2017/11/11 21:41:41.907739 main.go:451: encryption: aes
2017/11/11 21:41:41.907756 main.go:452: nodelay parameters: 0 30 2 1
2017/11/11 21:41:41.907770 main.go:453: sndwnd: 1024 rcvwnd: 1024
2017/11/11 21:41:41.907785 main.go:454: compression: true
2017/11/11 21:41:41.907793 main.go:455: mtu: 1350
2017/11/11 21:41:41.907808 main.go:456: datashard: 10 parityshard: 3
2017/11/11 21:41:41.907821 main.go:457: acknodelay: false
2017/11/11 21:41:41.907834 main.go:458: dscp: 0
2017/11/11 21:41:41.907848 main.go:459: sockbuf: 4194304
2017/11/11 21:41:41.907861 main.go:460: keepalive: 10
2017/11/11 21:41:41.907874 main.go:461: snmplog: 
2017/11/11 21:41:41.907888 main.go:462: snmpperiod: 60
2017/11/11 21:41:41.907904 main.go:463: usemul: false
2017/11/11 21:41:41.907921 main.go:464: udp mode: false
2017/11/11 21:41:41.907937 main.go:465: pprof listen at: 
2017/11/11 21:41:41.907953 main.go:466: default proxy: false
2017/11/11 21:41:41.907969 main.go:467: shadowsocks proxy: true
2017/11/11 21:41:41.907978 main.go:468: shadowsocks method: multi
2017/11/11 21:41:41.907991 main.go:469: shadowsocks key: passwd
但是用ss客户端始终无法连接

**Comment by ccsexyz** [comment]
ss 客户端使用的什么加密方式

**Comment by linyuhc001** [comment]
尝试了chacha20 salsa20 rc4-md5

**Comment by ccsexyz** [comment]
kcpraw 客户端使用的参数是什么

**Comment by linyuhc001** [comment]
啊？还是需要kcpraw客户端- -？？

**Comment by ccsexyz** [comment]
我不是很懂你的意思

**Comment by linyuhc001** [comment]
我以为服务端开了--ssproxy的情况下 客户端直接用ss客户端连接，但是好像还是要通过kcpraw客户端，所以我一直连不上。。

**Comment by ccsexyz** [comment]
因为 kcptun 一个常见的使用场景是加速 ss,  ss-client <--> kcp-client <--> kcp-server <--> ss-server 

ssproxy 这个参数的目的是省去最后的 ss-server.

**Comment by linyuhc001** [comment]
嗯嗯，明白了，谢谢
