### ISSUE TITLE
可以在ssr上使用吗？

### ISSUE THREAD

**Issue by yjd** [ccsexyz/kcpraw#33]
昨天刚看到这个kcpraw👍。之前一直用kcptun套在ssr里用。
尝试配置如下
server：
./kcpraw_server_linux_amd64 -l :996 -t 127.0.0.1:80 --key "123" --mtu 1400 --mode fast3 --nocomp --udp
client
kcpraw_client_windows_amd64.exe -l 0.0.0.0:8092 -r ip:996 --key "123" --mode fast3 --mtu 1400 --nocomp --udp
没有成功。

ssr的本地和远程的配置没动。一直用着kcptun。

浏览器 -- ssr:8088 -- 127.0.0.1:8092 -- Remote:996 -- 127.0.0.1:80(ssr)

看客户端打印也没什么错误：
2017/11/11 23:47:13.646437 main.go:927: session marked as expired
2017/11/11 23:47:13.648439 main.go:292: stream opened
2017/11/11 23:47:14.440734 main.go:933: session normally closed
2017/11/11 23:47:15.416891 main.go:292: stream opened
2017/11/11 23:47:43.648714 main.go:296: stream closed
2017/11/11 23:47:43.648714 main.go:296: stream closed
2017/11/11 23:47:43.886912 main.go:927: session marked as expired
2017/11/11 23:47:43.888909 main.go:292: stream opened
2017/11/11 23:47:44.441169 main.go:933: session normally closed
2017/11/11 23:47:44.859729 main.go:292: stream opened
2017/11/11 23:48:13.651070 main.go:292: stream opened
2017/11/11 23:48:13.889094 main.go:296: stream closed
2017/11/11 23:48:13.889094 main.go:296: stream closed
2017/11/11 23:48:13.889094 main.go:296: stream closed
2017/11/11 23:48:15.052430 main.go:927: session marked as expired
2017/11/11 23:48:15.053431 main.go:292: stream opened
2017/11/11 23:48:15.440709 main.go:933: session normally closed
2017/11/11 23:48:44.094090 main.go:292: stream opened
2017/11/11 23:48:45.054256 main.go:296: stream closed
2017/11/11 23:48:45.054256 main.go:296: stream closed
2017/11/11 23:49:10.643479 main.go:927: session marked as expired
2017/11/11 23:49:10.645481 main.go:292: stream opened
2017/11/11 23:49:10.872951 main.go:292: stream opened
2017/11/11 23:49:11.440257 main.go:933: session normally closed
2017/11/11 23:49:15.261514 main.go:292: stream opened
2017/11/11 23:49:40.845720 main.go:296: stream closed
2017/11/11 23:49:41.078784 main.go:296: stream closed
2017/11/11 23:49:45.463103 main.go:296: stream closed

x。突然又好了。问题解决。。

**Comment by ccsexyz** [comment]
额，为啥要使用 udp 选项呢，使用了 udp 就和 kcptun 一样了。

**Comment by yjd** [comment]
想试试哪个快😀
测试结果udp方式比较快。这项目都一年多了昨天才发现，相当于加强版可以独立运行也可以套着运行。比kcptun方便。tcp，udp又可以随时切换。👍

刚才的问题可能是时区问题，之前没发现差了8小时。但是之前kcptun，ssr能正常用没注意到。刚改了重启下就正常了。

**Comment by ccsexyz** [comment]
tcp 和 udp 大约速度会差多少呢？
😄 没有一年多，大约 3/4 年。

**Comment by yjd** [comment]
这么久。😔昨天才发现。

速度走tcp大概3000-7000 youtube，开udp偶尔会飙到一万多。还得多测试下，这台vps掉包比较多40%。

准备开2个进程一个给ssr用。一个给本地的cow用。
浏览器 --cow:8089--  127.0.0.1:8092(proxy) -- Remote:996(proxy)

刚又解决了个问题CreateProcess第一参数没写对。导致启动kcpraw就会闪退。

**Comment by yjd** [comment]
同配置看y2，开关udp选项
tcp  12600
udp 27000

**Comment by ccsexyz** [comment]
我觉得挺正常的。udp 没被限制而且速度更快的话，用 udp 就好了。

**Comment by wangyu-** [comment]
有些运营商会把tcp/udp/icmp数据用不同的路由策略发送出去；有时udp的线路比tcp好，把udp变成tcp会反而效果变差。不是很常见，但是会发生。

**Comment by yjd** [comment]
恩。感谢各位解答。^_^
