### ISSUE TITLE
SS代理怎么用？

### ISSUE THREAD

**Issue by lishen226** [ccsexyz/kcpraw#34]
我看只有服务端有SS代理的设置参数

**Comment by yjd** [comment]
我理解就是服务端省去了安装一个ss服务端。
客户端
浏览--ss客户端--kcpraw客户端--远端kcprw服务端

**Comment by lishen226** [comment]
@yjd 我搞明白了，是你说的这样
是不是udp没办法处理了？

**Comment by ccsexyz** [comment]
服务端启用 proxy 选项，客户端启用 udprelay 和 proxy，就可以转发 udp 数据了。

**Comment by ccsexyz** [comment]
在这种情况下客户端使用的协议是 socks5，把 sstap 或者类似的程序的地址设置为客户端的地址就可以了，协议选择 socks5.
shadowsocks 协议的 udp 部分要支持也是很简单的，但是现在还没有支持的动力。

**Comment by lishen226** [comment]
socks5感觉有点慢哈，晚上回去跑gta5试试

**Comment by ccsexyz** [comment]
> socks5感觉有点慢哈

这里的慢具体是怎么得出的结论呢？

**Comment by lishen226** [comment]
在speedtest网站上测速，我宽带是20M，SS一般都是瞬间满速，socks5一般是15M左右而且是缓慢增长到15M
socks5好像是用别的工具时测的（udp2raw+gost(kcp&socks5)），等晚上回去我再测测

**Comment by lishen226** [comment]
用SS和SOCKS5分別测试了下，正如我之前所说，SS延迟200，SOCKS5延迟300
SS服务端参数
nohup ./kcpraw_server_linux_amd64 -l 0.0.0.0:9222 -t :8990 --key lincoln --mtu 1200 --mode fast3 --ds 0 --ps 0 --nocomp --ssproxy --ssmethod aes-256-cfb --sskey lincoln >/dev/null 2>1 &
SOCKS5服务端参数
nohup ./kcpraw_server_linux_amd64 -l 0.0.0.0:9111 -t :8080 --key lincoln --mtu 1200 --mode fast3 --ds 0 --ps 0 --nocomp --proxy >/dev/null 2>1 &

**Comment by ccsexyz** [comment]
使用 socks5 时客户端启用 proxy 了吗

**Comment by lishen226** [comment]
启用了

**Comment by ccsexyz** [comment]
并不能复现你说的情况
这是使用 proxy 的测试结果

<img width="1043" alt="2017-11-14 1 55 28" src="https://user-images.githubusercontent.com/13003124/32765049-b0ebf414-c943-11e7-9cc9-069a6129354c.png">

这是使用 ssproxy 的测试结果
<img width="796" alt="2017-11-14 1 56 36" src="https://user-images.githubusercontent.com/13003124/32765066-c435bf3c-c943-11e7-9391-ae286db3fc0d.png">

**Comment by lishen226** [comment]
可能是网络环境的差异吧
我今天又测了下，下载速度两种相当，socks5延迟比ss高10-20

**Comment by ccsexyz** [comment]
10-20 说明基本没差别
