### ISSUE TITLE
V20171114版在Nexus6 lineageos14.1联网问题请教。

### ISSUE THREAD

**Issue by wansen** [ccsexyz/kcpraw#36]
首先感谢开发者开发的这个程序。
在VPS配置了一个V20171114版server端，运行一个进程。
在手机Nexus6P android 8.1上运行一个arm64客户端，正常使用。
在Nexus6上运行另一个arm7客户端，同上配置，在日志中看到可以正常和服务端连接，但就是无数据交换。日志走到：2017//11/20 19：89：64.198964 main.go:739: connection:192.168.1.10:40008 -> xx.xx.xx.xx:18964这一步就停止，查看进程，在运行中。使用程序在本地监听端口上网，日志无动静，也不能上网，估计是无数据交换。
两客户端同样配置，如下：
{
    "localaddr": ":8964",
    "remoteaddr": "xx.xx.xx.xx:18964",
    "key": "xxxxxxxxxxxxx",
    "crypt": "salsa20",
    "mode": "fast3",
    "mtu": 1200,
    "sndwnd": 1024,
    "rcvwnd": 4096,
    "proxy": true,
    "nocomp": true,
    "host": "v.baidu.com"
}
请开发者或其他懂的专业人士在有空时不吝指教，谢谢！
另外请教一下开发者，怎么编译好的程序都不能下载了？看来不得不学android编译了。

**Comment by ccsexyz** [comment]
sorry, this project has been deprecated and I won't release precompiled binary any more.

**Comment by wansen** [comment]
不论怎样，都要谢谢你曾经的付出。
