### ISSUE TITLE
Why deprecated?

### ISSUE THREAD

**Issue by ch3n2k** [ccsexyz/kcpraw#37]
Att.

**Comment by yjd** [comment]
这才刚用没几天

**Comment by ch3n2k** [comment]
从最后commit删除ss相关功能来看，可能是被警告了

**Comment by ccsexyz** [comment]
of course not, I just remove an option to set the password of shadowsocks.sskey is equal to the key of kcptun now.

**Comment by yjd** [comment]
这个项目有用，不维护也希望不要删除。就用最后一个版本好了，好像是47也被删了。
上周就遇到几次kcptun被拦了。走raw就ok了。过会udp又恢复了。

**Comment by hdstar2009** [comment]
项目废弃了？不更新还是换成其他项目？

**Comment by eromoe** [comment]
Why deprecated ? +1 .   Any alternative recommand @ccsexyz ?

**Comment by ccsexyz** [comment]
`
Would you integrate kcpraw function into https://github.com/ccsexyz/kcptun-asio ?
`
Nope.
