### ISSUE TITLE
Freebsd编译的客户端出现Retry too many times错误

### ISSUE THREAD

**Issue by Dakai** [ccsexyz/kcpraw#4]
2017/05/04 01:58:44 main.go:309: version: SELFBUILD
2017/05/04 01:58:44 main.go:345: listening on: [::]:499
2017/05/04 01:58:44 main.go:346: encryption: none
2017/05/04 01:58:44 main.go:347: nodelay parameters: 1 10 2 1
2017/05/04 01:58:44 main.go:348: remote address: 108.61.247.59:29510
2017/05/04 01:58:44 main.go:349: sndwnd: 2048 rcvwnd: 2048
2017/05/04 01:58:44 main.go:350: compression: false
2017/05/04 01:58:44 main.go:351: mtu: 1400
2017/05/04 01:58:44 main.go:352: datashard: 10 parityshard: 3
2017/05/04 01:58:44 main.go:353: acknodelay: false
2017/05/04 01:58:44 main.go:354: dscp: 0
2017/05/04 01:58:44 main.go:355: sockbuf: 4194304
2017/05/04 01:58:44 main.go:356: keepalive: 10
2017/05/04 01:58:44 main.go:357: conn: 1
2017/05/04 01:58:44 main.go:358: autoexpire: 0
2017/05/04 01:58:44 main.go:359: snmplog:
2017/05/04 01:58:44 main.go:360: snmpperiod: 60
2017/05/04 01:58:44 main.go:361: scavengettl: 600
2017/05/04 01:58:44 main.go:366: httphost:
2017/05/04 01:58:45 main.go:89: retry too many times
net.DialRAW
github.com/ccsexyz/kcp-go-raw.DialWithOptions
        /root/go/src/github.com/ccsexyz/kcp-go-raw/sess.go:34
main.main.func1.1
        /usr/share/kcpraw/kcpraw-20170330/client/main.go:374
main.main.func1
        /usr/share/kcpraw/kcpraw-20170330/client/main.go:416
github.com/urfave/cli.HandleAction
        /root/go/src/github.com/urfave/cli/app.go:485
github.com/urfave/cli.(*App).Run
        /root/go/src/github.com/urfave/cli/app.go:259
main.main
        /usr/share/kcpraw/kcpraw-20170330/client/main.go:455

问问题前先搜索ISSUE，并搞清楚下面的问题:

1. 检查 ```-key xxx``` 至少三遍, ***保证***两边一致。
2. 保证```-nocomp, -datashard, -parityshard,  -key, -crypt```两边一致。
3. 是否在服务器端，正确设定了转发的目标服务器地址 ***--target***。
4. 如果第3条不确定，尝试在服务器上telnet target port试试。
5. 防火墙是否关闭了UDP通信。
6. 两端的版本是否一致？
7. 是不是最新版本？
8. 两端分别是什么操作系统？
9. 两端的输出日志是什么？

Before firing issue, make sure you figured out the following common questions.

PLEASE DO SEARCH FIRST.

1. Check your ```-key xxx``` for at least 3 times, ***MAKE SURE*** both sides share the same secret.
2. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.
3. Did you correctly set the ***-target*** on the server side?
4. ***MAKE SURE*** ```telnet target port``` on your server successful(don't ask me why couldn't).
5. Does your ***firewall allows UDP*** communications? (including your ISP Cable-Modem)
6. Are you using the **same version** for both client & server
7. Are you using the **latest release**?
8. Which **OS** do you use?
9. Which end for this issue related to, **client or server**?

**Comment by ccsexyz** [comment]
确定服务端是在运行吗,可以直接用telnet连接服务端ip:port试试看

**Comment by Dakai** [comment]
服务端在运行中，不过kcpraw运行的参数和kcptun不一样，监听的是“IP:端口”而不是Kcptun的“:端口”，我用了同一个服务器也是SS服务器的IP，不知道这样对不对

**Comment by ccsexyz** [comment]
我试了一下连接日志里的ip:port，应该是服务端没有启动

**Comment by Dakai** [comment]
服务器端已经control+C关闭了，我现在装个Debian的再试下

**Comment by ccsexyz** [comment]
最好能有tcpdump的抓包记录, tcpdump host kcp-server-ip and port kcp-server-port and proto tcp

**Comment by Dakai** [comment]
第一次运行tcpdump有输出，不过参数没搞对，之后tcpdump都没输出了，在Debian上试了会出现Rest by peer, 加了-ignrst之后也是retry too many times

**Comment by ccsexyz** [comment]
这样吧,我提供一个测试服务器你试试看
在本地执行,
```
client -r 120.77.179.172:9999 -l :9999
```
另起一个终端执行
```
curl -v localhost:9999 -H 'Host: www.baidu.com'
```

**Comment by Dakai** [comment]
还是一样
root@kcptun:/usr/share/kcpraw # ./client -r 120.77.179.172:9999 -l :9999
2017/05/04 03:24:25 main.go:309: version: SELFBUILD
2017/05/04 03:24:25 main.go:345: listening on: [::]:9999
2017/05/04 03:24:25 main.go:346: encryption: aes
2017/05/04 03:24:25 main.go:347: nodelay parameters: 0 30 2 1
2017/05/04 03:24:25 main.go:348: remote address: 120.77.179.172:9999
2017/05/04 03:24:25 main.go:349: sndwnd: 128 rcvwnd: 512
2017/05/04 03:24:25 main.go:350: compression: true
2017/05/04 03:24:25 main.go:351: mtu: 1350
2017/05/04 03:24:25 main.go:352: datashard: 10 parityshard: 3
2017/05/04 03:24:25 main.go:353: acknodelay: false
2017/05/04 03:24:25 main.go:354: dscp: 0
2017/05/04 03:24:25 main.go:355: sockbuf: 4194304
2017/05/04 03:24:25 main.go:356: keepalive: 10
2017/05/04 03:24:25 main.go:357: conn: 1
2017/05/04 03:24:25 main.go:358: autoexpire: 0
2017/05/04 03:24:25 main.go:359: snmplog:
2017/05/04 03:24:25 main.go:360: snmpperiod: 60
2017/05/04 03:24:25 main.go:361: scavengettl: 600
2017/05/04 03:24:25 main.go:366: httphost:
2017/05/04 03:24:30 main.go:89: retry too many times
net.DialRAW
github.com/ccsexyz/kcp-go-raw.DialWithOptions
        /root/go/src/github.com/ccsexyz/kcp-go-raw/sess.go:34
main.main.func1.1
        /usr/share/kcpraw/kcpraw-20170330/client/main.go:374
main.main.func1
        /usr/share/kcpraw/kcpraw-20170330/client/main.go:416
github.com/urfave/cli.HandleAction
        /root/go/src/github.com/urfave/cli/app.go:485
github.com/urfave/cli.(*App).Run
        /root/go/src/github.com/urfave/cli/app.go:259
main.main
        /usr/share/kcpraw/kcpraw-20170330/client/main.go:455
runtime.main
        /usr/local/go/src/runtime/proc.go:185
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2197
createConn()
main.main.func1.1
        /usr/share/kcpraw/kcpraw-20170330/client/main.go:376
main.main.func1
        /usr/share/kcpraw/kcpraw-20170330/client/main.go:416
github.com/urfave/cli.HandleAction
        /root/go/src/github.com/urfave/cli/app.go:485
github.com/urfave/cli.(*App).Run
        /root/go/src/github.com/urfave/cli/app.go:259
main.main
        /usr/share/kcpraw/kcpraw-20170330/client/main.go:455
runtime.main
        /usr/local/go/src/runtime/proc.go:185
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2197

> curl -v localhost:9999 -H 'Host: www.baidu.com'
结果：

root@kcptun:/usr/share/kcpraw # curl -v localhost:9999 -H 'Host: www.baidu.com'
* Rebuilt URL to: localhost:9999/
*   Trying ::1...
* connect to ::1 port 9999 failed: Connection refused
*   Trying 127.0.0.1...
* connect to 127.0.0.1 port 9999 failed: Connection refused
* Failed to connect to localhost port 9999: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 9999: Connection refused

**Comment by ccsexyz** [comment]
额，你再执行一次吧，我看看抓包记录

**Comment by Dakai** [comment]
还是一样的Retry too many times。。

**Comment by ccsexyz** [comment]
本地没有drop掉RST包导致的

**Comment by ccsexyz** [comment]
你本地是什么系统？freebsd的话参考一下readme里mac下的解决办法吧
