### ISSUE TITLE
服务端无端口监听

### ISSUE THREAD

**Issue by wuyanteng** [ccsexyz/kcpraw#46]
服务器CentOS7 使用了最新的版本，出现如下情况：请问怎么破？谢谢

[root@kvm ~]# kcpraw_server_linux_amd64 -v
kcpraw version 20171121
[root@kvm ~]#

[root@kvm ~]# /usr/sbin/kcpraw_server_linux_amd64 -l ":29900" -t "xx.xx.xx.xx:443"
2019/03/05 05:07:29.816121 main.go:401: version: 20171121
2019/03/05 05:07:29.829367 main.go:438: listening on: 0.0.0.0:29900
2019/03/05 05:07:29.829397 main.go:439: target: xx.xx.xx.xx:443
2019/03/05 05:07:29.829418 main.go:440: encryption: aes
2019/03/05 05:07:29.829427 main.go:441: nodelay parameters: 0 30 2 1
2019/03/05 05:07:29.829435 main.go:442: sndwnd: 1024 rcvwnd: 1024
2019/03/05 05:07:29.829442 main.go:443: compression: true
2019/03/05 05:07:29.829450 main.go:444: mtu: 1350
2019/03/05 05:07:29.829457 main.go:445: datashard: 10 parityshard: 3
2019/03/05 05:07:29.829464 main.go:446: acknodelay: false
2019/03/05 05:07:29.829471 main.go:447: dscp: 0
2019/03/05 05:07:29.829478 main.go:448: sockbuf: 4194304
2019/03/05 05:07:29.829485 main.go:449: keepalive: 10
2019/03/05 05:07:29.829493 main.go:450: snmplog: 
2019/03/05 05:07:29.829500 main.go:451: snmpperiod: 60
2019/03/05 05:07:29.829507 main.go:452: usemul: false
2019/03/05 05:07:29.829514 main.go:453: udp mode: false
2019/03/05 05:07:29.829521 main.go:454: pprof listen at: 
2019/03/05 05:07:29.829531 main.go:455: default proxy: false
2019/03/05 05:07:29.829539 main.go:456: shadowsocks proxy: false

[root@kvm ~]# ss -lntup|grep 29900
[root@kvm ~]#

**Comment by ccsexyz** [comment]
```
ss -lwnp
State       Recv-Q Send-Q                                  Local Address:Port                                    Peer Address:Port
UNCONN      0      0                                     xxxxxxxxxx:6                                                  *:*      users:(("kcpraw_server_l",27306,3))
```
