### ISSUE TITLE
darwin是为win发布的预编译版本吗

### ISSUE THREAD

**Issue by charli2014** [ccsexyz/kcpraw#5]
你好！
darwin是为win发布的预编译版本吗，我在win8.1 64bit系统下运行提示不兼容。。。

**Comment by ccsexyz** [comment]
darwin是mac下的，windows下的就叫windows

**Comment by charli2014** [comment]
不好意思啊，对darwin不是很明白。感谢回复。
另外，
release中latest最新版的日期是20170330，没看见4月26号的。
最早的有win的版本就是20170227。

**Comment by ccsexyz** [comment]
@charli2014 看走眼了。。。
