### ISSUE TITLE
cannot find correct interface net.DialRAW

### ISSUE THREAD

**Issue by zvit1** [ccsexyz/kcpraw#6]
我使用的是win10的客户端，运行以后报这个错，请问这个怎么解决啊？
`cannot find correct interface net.DialRAW`

**Comment by ccsexyz** [comment]
你remoteaddr填的是什么

**Comment by zvit1** [comment]
服务端的是 -l "<ip>:299001"
客户端对应的也是 "<ip>:299001"

**Comment by ccsexyz** [comment]
不太好判断是哪儿有问题，抱歉

**Comment by zvit1** [comment]
好吧，谢谢你的回复，我再弄弄看，如果有结果了再来反馈。
对了，我是直接下载的编译好的windows客户端，然后本地装有winpcap，还有golang官网上面直接下载了一个安装包安装的go，这样提供了完整的运行环境了吗？

**Comment by ccsexyz** [comment]
直接下载预编译的可执行文件的话只需要winpcap就可以了

**Comment by zvit1** [comment]
另外还有一个问题额，就是如果我用supervisor来在服务端运行kcpraw的话，会报这个错，但是直接运行的话就不会。

    2017/07/18 03:16:51 version: 20170428
    2017/07/18 03:16:51 listen ip4:tcp 23.94.223.*: socket: operation not permitted
    net.ListenRAW
    github.com/ccsexyz/kcp-go-raw.ListenWithOptions
      /Users/johnsonjohn/Go/src/github.com/ccsexyz/kcp-go-raw/sess.go:48
    main.main.func1
      /Users/johnsonjohn/Go/src/github.com/ccsexyz/kcpraw/server/main.go:338
    github.com/urfave/cli.HandleAction
      /Users/johnsonjohn/Go/src/github.com/urfave/cli/app.go:485
    github.com/urfave/cli.(*App).Run
      /Users/johnsonjohn/Go/src/github.com/urfave/cli/app.go:259
    main.main
      /Users/johnsonjohn/Go/src/github.com/ccsexyz/kcpraw/server/main.go:385
    runtime.main
      /usr/local/go/src/runtime/proc.go:185
    runtime.goexit
      /usr/local/go/src/runtime/asm_amd64.s:2197

这个我也没有搜索到解决的办法……

**Comment by ccsexyz** [comment]
supervisor需要用root权限运行，并且不要在配置文件里配置user

**Comment by zvit1** [comment]
我是直接使用的root用户，然后试了下把user配置直接去掉还是没有用额，报一样的错误……

**Comment by zvit1** [comment]
终于查到了……supervisor的问题解决了，配置文件加了suid，然后配置里面配置了一个user

`chmod u+s /usr/local/kcpraw/kcpraw_server_linux_amd64`

希望能对后面跟我一样小白的人有所帮助……

**Comment by zvit1** [comment]
这样的话，可能客户端也是权限不足的问题，客户端出问题是在家里的电脑上，等晚上回家了以后去试一下再来反馈

**Comment by zvit1** [comment]
回家试了下，客户端应该也是权限的问题，我换了管理员用户运行，现在就没问题了。
