### ISSUE TITLE
你好，关于端口问题请教。

### ISSUE THREAD

**Issue by baggiogogo** [ccsexyz/kcpraw#7]
使用上一切正常，只是不太清楚是否因为伪装了http的缘故需要用80端口？用其他端口是否需要--nohttp，谢谢。

**Comment by ccsexyz** [comment]
没有这个限制

**Comment by baggiogogo** [comment]
pkts bytes target     prot opt in     out     source               destination
982 39280 DROP     tcp  --  any    any     localhost            X.X.X.X         tcp spt:43565 dpt:37372 flags:RST/RST

请帮我看看这个生成的客户端iptables是否正常，出现一个问题，就是tumblr小视频无法观看，或断断续续，找不到原因，怀疑是iptables。

本来是一切正常的，后来调整了下supervisor顺序就莫名出问题了，用于树莓派ss-redir，我记得原来source地址可以显示192.168.X.X,现在变成localhost，另外服务器防火墙会阻挡吗？我只简单写了几条，打开相应入站端口，最后全部DROP。

**Comment by ccsexyz** [comment]
只有tumblr小视频抽风吗

**Comment by baggiogogo** [comment]
稍等，我正在测试，我记得一直摆在小视频窗口让它等待，有一定几率完全断流。

**Comment by ccsexyz** [comment]
完全断流指的是kcpraw完全无法使用了吗

**Comment by baggiogogo** [comment]
是的，网页都打不开。

**Comment by ccsexyz** [comment]
那就有问题了，用iptabels抓包看看，以及检查下是不是iptables规则被改掉了

**Comment by baggiogogo** [comment]
目前无法复现全部断掉的状态，与此同时推特视频都是正常的，我记得原来用原版KCPTUN也有类似的问题，但那是打开了ss的udp转发状态下。
晕，拍三下脑袋，好像昨天是打开了UDP转发，我关掉再试验。
麻烦您了，有结果我会及时反馈,谢谢.

**Comment by ccsexyz** [comment]
恩。问题复现了再反馈。
我这边用着还是稳如狗的。

**Comment by baggiogogo** [comment]
好的，谢谢。

**Comment by baggiogogo** [comment]
hi
我确信是服务器iptables的问题，关了只留自动生成的这条就没问题，请教下你的服务器iptables是怎么写的，谢谢。

**Comment by ccsexyz** [comment]
是有其他程序修改iptables吗？让 kcpraw 比那个程序晚启动就可以了。也可以手动复制一份生成的规则到output链头部。

**Comment by baggiogogo** [comment]
没有，就是简单的安全规则，如果全部accept，仅留kcpraw自动生成的一条，就没有问题。
![default](https://user-images.githubusercontent.com/21306212/28562716-ff352956-7155-11e7-8f8b-30726710c00f.JPG)
![1](https://user-images.githubusercontent.com/21306212/28562723-058f9426-7156-11e7-88e1-b958314af942.JPG)

**Comment by baggiogogo** [comment]
好的，明白，我再研究研究看，谢谢了。
