### ISSUE TITLE
安卓手机连接不成功

### ISSUE THREAD

**Issue by chuangdi** [ccsexyz/kcpraw#8]
安卓可以启动arm版本，但连接不了服务器，服务器上成功执行，但是用netstat命令看不到监听端口，而原版正常能看到监听端口，服务器log文件显示客户端地址，但broken pipe,请问有没有成功的案例？安卓版本6.0.1，已root。

**Comment by ccsexyz** [comment]
在服务端加上ignrst选项试试

**Comment by chuangdi** [comment]
好的，试试再来。谢谢。

**Comment by ccsexyz** [comment]
其实我个人认为在手机上用意义不大。

**Comment by chuangdi** [comment]
既然有host和x-online-host,那意义大了，嘿嘿。

**Comment by chuangdi** [comment]
加了ignrst,服务器启动日志正常，可为什么还是看不到监听端口，用的netstat -antup。

**Comment by chuangdi** [comment]
我的服务器是centos 6.5,内核4.12

**Comment by ccsexyz** [comment]
看来你已经猜到最初为什么要加host了。
看不到是正常的。

**Comment by chuangdi** [comment]
加了ignrst参数还是不行，防火墙除了tcp监听端口还需要开什么端口吗，连不上。

**Comment by ccsexyz** [comment]
抓下包看看吧

**Comment by chuangdi** [comment]
好像是可以了，估计是dns的问题，我用dnrd本地dns可以上youtube，可能ss-dir转发不了http的dns包。
