### ISSUE TITLE
windows使用编译好的客户端，无法成功运行

### ISSUE THREAD

**Issue by liangxyz** [ccsexyz/kcpraw#9]
如题，系统环境：win10 15063 x64，已经安装最新版wincap
使用您的编译好的客户端，无法正常运行，截图如下
![snipaste_20170807_095051](https://user-images.githubusercontent.com/8108927/29009561-ea222892-7b56-11e7-82b1-aed598386533.png)

服务器端参数和运行结果如下

请问是哪里出了问题？不胜感激，谢谢您！

**Comment by ccsexyz** [comment]
从图上来看服务端监听地址写的127.0.0.1，这里应该写服务端ip地址。如果还不行的话在服务器用tcpdump抓包试试。tcpdump host <ip> and port <port>。
ps:xshell下方会显示服务器的ip地址。

**Comment by liangxyz** [comment]
谢谢作者，你的意思是，我服务器设置有问题，导致客户端连不上是吗？

**Comment by liangxyz** [comment]
我感觉我的Windows客户端运行不正常，底下那么多c盘的文件我都没有

**Comment by ccsexyz** [comment]
1.如果是127的话是肯定不行的，你改成ip地址试试。
2.设置好服务端后一个简单的验证办法是从本地用telnet连接服务端，telnet ip port,服务端正常工作是能够连接成功的。
3.那些文件都在我电脑上，不要惊慌，go就是这样的。

**Comment by ccsexyz** [comment]
有很多issue都是因为一些简单的配置问题导致的，感觉是我不喜欢好好写文档的锅。

**Comment by liangxyz** [comment]
经过测试，确实是服务器端没有正常运行，我查看了运行的进程和端口，都没看见kcpraw对应的信息，但是我是按照您首页的最基本参数运行的，/usr/local/kcptun/kcpraw_server_linux_amd64 -t "127.0.0.1:9125" -l "xxxxxxxx:12500"，
![snipaste_20170807_112158](https://user-images.githubusercontent.com/8108927/29011076-c04b95a6-7b62-11e7-80ce-21810ed1b8c2.png)

**Comment by liangxyz** [comment]
我下载的是https://github.com/ccsexyz/kcpraw/releases/download/v20170227/kcptun-windows-amd64-20170301.zip这个windows客户端，服务器端用的是最新0802版本的，请问没有影响吧？

**Comment by ccsexyz** [comment]
没有影响。
我判断应该是你的防火墙把端口给屏蔽了。

**Comment by liangxyz** [comment]
应该不会，我原来用的是一键安装kcptune（https://blog.kuoruan.com/110.html），可以正常运行，后来我发现有udp断流现象，就想试试您的程序，结果不行，我所有的设置几乎没变。

**Comment by ccsexyz** [comment]
我注意到你防火墙上的规则似乎清除了，你可以别用这个脚本直接执行可执行程序试试。

**Comment by ccsexyz** [comment]
刚才我对代码进行了一些改动，现在linux服务端会自动增加一条准入规则。

**Comment by liangxyz** [comment]
全新安装的debian 8.0 x64，安装好SSR以后，下载新版amd64服务器端，放在root目录下，设置755权限，使用 ./kcpraw_server_linux_amd64 -t "127.0.0.1:9125" -l "67.21.74.145:12500"这条命令运行，结果如下
![snipaste_20170807_150546](https://user-images.githubusercontent.com/8108927/29015775-fe8e43d0-7b81-11e7-878e-aff9eca36933.png)
请问您能通过这个参数链接上我的服务器吗？我在自己电脑上运行windows端，还是无法连接，日志如下

> *************************** begin ***************************
2017/08/07 15:03:03 main.go:309: version: SELFBUILD
2017/08/07 15:03:03 main.go:345: listening on: [::]:9125
2017/08/07 15:03:03 main.go:346: encryption: aes
2017/08/07 15:03:03 main.go:347: nodelay parameters: 0 30 2 1
2017/08/07 15:03:03 main.go:348: remote address: 67.21.74.145:12500
2017/08/07 15:03:03 main.go:349: sndwnd: 1024 rcvwnd: 1024
2017/08/07 15:03:03 main.go:350: compression: true
2017/08/07 15:03:03 main.go:351: mtu: 1350
2017/08/07 15:03:03 main.go:352: datashard: 10 parityshard: 3
2017/08/07 15:03:03 main.go:353: acknodelay: false
2017/08/07 15:03:03 main.go:354: dscp: 0
2017/08/07 15:03:03 main.go:355: sockbuf: 4194304
2017/08/07 15:03:03 main.go:356: keepalive: 10
2017/08/07 15:03:03 main.go:357: conn: 1
2017/08/07 15:03:03 main.go:358: autoexpire: 0
2017/08/07 15:03:03 main.go:359: snmplog: 
2017/08/07 15:03:03 main.go:360: snmpperiod: 60
2017/08/07 15:03:03 main.go:361: scavengettl: 600
2017/08/07 15:03:03 main.go:366: httphost:  
2017/08/07 15:03:07 main.go:89: retry too many times
net.DialRAW
github.com/ccsexyz/kcp-go-raw.DialWithOptions
	C:/WhyGo/src/github.com/ccsexyz/kcp-go-raw/sess.go:15
main.main.func1.1
	C:/WhyGo/src/github.com/ccsexyz/kcptun/client/main.go:373
main.main.func1
	C:/WhyGo/src/github.com/ccsexyz/kcptun/client/main.go:425
github.com/urfave/cli.HandleAction
	C:/WhyGo/src/github.com/urfave/cli/app.go:485
github.com/urfave/cli.(*App).Run
	C:/WhyGo/src/github.com/urfave/cli/app.go:259
main.main
	C:/WhyGo/src/github.com/ccsexyz/kcptun/client/main.go:470
runtime.main
	C:/Go/src/runtime/proc.go:183
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:2086
createConn()
main.main.func1.1
	C:/WhyGo/src/github.com/ccsexyz/kcptun/client/main.go:375
main.main.func1
	C:/WhyGo/src/github.com/ccsexyz/kcptun/client/main.go:425
github.com/urfave/cli.HandleAction
	C:/WhyGo/src/github.com/urfave/cli/app.go:485
github.com/urfave/cli.(*App).Run
	C:/WhyGo/src/github.com/urfave/cli/app.go:259
main.main
	C:/WhyGo/src/github.com/ccsexyz/kcptun/client/main.go:470
runtime.main
	C:/Go/src/runtime/proc.go:183
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:2086
**************************** end ****************************


另外我在终端使用ctrl+c退出以后，会发现终端显示如下日志。
![snipaste_20170807_151227](https://user-images.githubusercontent.com/8108927/29016092-83d6d8ee-7b83-11e7-9a0f-c0651f7db79a.png)

使用iptables -L查看防火墙链接，确定12500端口已经添加了，同时也使用screen命令在后台运行服务端。
![snipaste_20170807_153425](https://user-images.githubusercontent.com/8108927/29016685-015e8724-7b86-11e7-8ad8-675e6d4cb404.png)

然而就是连不上，真的很奇怪，我在手机使用ssr app 手动添加参数，显示能连上，但是测试链接，提示链接被peer关闭。

请问怎么才能连上服务器呢？

**Comment by ccsexyz** [comment]
我这边连接是ok的。

windows 客户端参考 [windows firewall port exceptions](https://www.veritas.com/support/en_US/article.000085856) 链接中的方法为 LOCAL_PORT 设置防火墙规则  
如果找不到方法过滤 RST 报文,现在可以使用选项 --ignrst 来在应用层忽略 RST 报文，客户端和服务端都加上吧

**Comment by liangxyz** [comment]
请问能给一个客户端连接的具体参数吗？谢谢

**Comment by ccsexyz** [comment]
客户端这边不用变，在服务端启动参数后面加上--ignrst

**Comment by ccsexyz** [comment]
win这边去修改防火墙规则可能操作起来会比较麻烦，而且某些杀毒软件还会接管防火墙，直接在服务端忽略rst可能比较好。

**Comment by ccsexyz** [comment]
后面我会去尝试像linux上一样自动增删防火墙规则。

**Comment by liangxyz** [comment]
谢谢，我发现原来是我没有设置windows防火墙的原因，我看说明，以为用了wincap就不用设置了。真的很抱歉，我的错。

**Comment by ccsexyz** [comment]
感觉还是程序写的不够好的原因，理想情况下上手难度应该和 kcptun 一样才对。

**Comment by wangyu-** [comment]
>win这边让用户去修改防火墙规则可能操作起来会比较麻烦，而且某些杀毒软件还会接管防火墙，直接在服务端忽略rst可能比较好。

忽略rst有些情况下可能不行，有的NAT设备在检测到了rst后会把NAT pipe掐掉。比如mac上的vmware带的NAT，收到rst NAT pipe就断。真实的路由如果也可能会这么做，可以更快得回收端口资源。

**Comment by ccsexyz** [comment]
忽略对懒得改防火墙又不会因为rst导致pipe被掐断的用户是比较友好的，真不行就想办法改防火墙呗。

**Comment by wangyu-** [comment]
也对。
